"""Infers and generates TypeScript interfaces from DataStore collections and singletons."""

from __future__ import annotations

from typing import Any, Dict, List, Set
from mock_api_py.store import DataStore


def _to_pascal_case(word: str) -> str:
    """Converts a snake_case or plural word to SingularPascalCase."""
    # Handle common plural suffixes
    lower = word.lower()
    if lower.endswith("ies"):
        singular = word[:-3] + "y"
    elif lower.endswith("ses") or lower.endswith("xes") or lower.endswith("ches") or lower.endswith("shes"):
        singular = word[:-2]
    elif lower.endswith("s") and not lower.endswith("ss") and len(lower) > 3:
        singular = word[:-1]
    else:
        singular = word

    # Convert snake_case or kebab-case
    parts = [p.capitalize() for p in singular.replace("-", "_").split("_") if p]
    return "".join(parts) if parts else word.capitalize()


def _infer_ts_type(value: Any) -> str:
    """Infers a TypeScript primitive or complex type from a Python value."""
    if value is None:
        return "any"
    if isinstance(value, bool):
        return "boolean"
    if isinstance(value, (int, float)):
        return "number"
    if isinstance(value, str):
        return "string"
    if isinstance(value, list):
        if not value:
            return "any[]"
        inner_type = _infer_ts_type(value[0])
        return f"{inner_type}[]"
    if isinstance(value, dict):
        return "Record<string, any>"
    return "any"


def generate_typescript_definitions(store: DataStore) -> str:
    """Generates a complete TypeScript definitions file based on store data."""
    lines: List[str] = [
        "/**",
        " * TypeScript Definitions",
        " * Auto-generated by mock-api-py",
        " */",
        "",
    ]

    collections = store.get_collections()
    singletons = store.get_singletons()
    db_properties: List[str] = []

    # 1. Process Collections
    for col_name in collections.keys():
        items = store.get_all(col_name)
        interface_name = _to_pascal_case(col_name)
        db_properties.append(f"  {col_name}: {interface_name}[];")

        # Collect all property names and their types across items
        all_keys: Set[str] = set()
        key_types: Dict[str, Set[str]] = {}
        key_counts: Dict[str, int] = {}

        for item in items:
            if isinstance(item, dict):
                for k, v in item.items():
                    all_keys.add(k)
                    key_counts[k] = key_counts.get(k, 0) + 1
                    t = _infer_ts_type(v)
                    if k not in key_types:
                        key_types[k] = set()
                    key_types[k].add(t)

        lines.append(f"export interface {interface_name} {{")
        total_items = len(items)

        # Ensure 'id' is first if present
        sorted_keys = sorted(all_keys, key=lambda k: (0 if k == "id" else 1, k))

        for k in sorted_keys:
            types_found = key_types.get(k, {"any"})
            ts_type = " | ".join(sorted(types_found))
            # If not present in all items, mark as optional
            optional = "?" if total_items > 0 and key_counts.get(k, 0) < total_items else ""
            lines.append(f"  {k}{optional}: {ts_type};")

        lines.append("}")
        lines.append("")

    # 2. Process Singletons
    for sin_name in singletons:
        data = store.get_singleton(sin_name) or {}
        interface_name = _to_pascal_case(sin_name)
        db_properties.append(f"  {sin_name}: {interface_name};")

        lines.append(f"export interface {interface_name} {{")
        for k, v in data.items():
            ts_type = _infer_ts_type(v)
            lines.append(f"  {k}: {ts_type};")
        lines.append("}")
        lines.append("")

    # 3. Overall Database Interface
    lines.append("export interface Database {")
    lines.extend(db_properties)
    lines.append("}")
    lines.append("")

    return "\n".join(lines)
